# Codecov configuration

codecov: 
 token: f0e98b56-ee56-4cf1-bf13-b852b19f9e66

# Ignore third-party directory completely (vendor / external deps)
ignore:
  - "third-party/**"

# Ignore third-party directory completely (vendor / external deps)
coverage:
  status:
    project:
      default:   # default is the status check's name, not default settings
        target: auto
        threshold: 5
        base: auto
        flags:
          - unit
        paths:
          - "include"
        branches:
          - main
        if_ci_failed: error # success, failure, error, ignore
        informational: false
        only_pulls: false

# Test reports (JUnit) for Codecov Test Analytics
# Codecov automatically scans for *junit.xml by default; include explicit path for clarity
tests:
  junit:
    - build/unit_tests_junit.xml
